<?php 
define('RATE_DETAILS_THICKNESS_VERSION', '1.0');
define('RATE_DETAILS_THICKNESS_FOLDER', 'rate_details_thickness');
define('RATE_DETAILS_THICKNESS_PATH', MODULES_PATH.RATE_DETAILS_THICKNESS_FOLDER.'/');
