<?php 
define('SLITTING_INSTRUCTION_VERSION', '1.0');
define('SLITTING_INSTRUCTION_FOLDER', 'slitting_instruction');
define('SLITTING_INSTRUCTION_PATH', MODULES_PATH.SLITTING_INSTRUCTION_FOLDER.'/');
