<?php 
define('TRANSFER_INSTRUCTION_VERSION', '1.0');
define('TRANSFER_INSTRUCTION_FOLDER', 'transfer_instruction');
define('TRANSFER_INSTRUCTION_PATH', MODULES_PATH.TRANSFER_INSTRUCTION_FOLDER.'/'); 



